name: Actualizar Infoleg

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  descargar:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <<< esto habilita el push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          pip install pandas requests

      - name: Ejecutar script de descarga
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        run: python scripts/descargar_infoleg.py

      - name: Subir datasets actualizados al repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/  # o cualquier otra carpeta pequeña
          git commit -m "Actualización automática de script Infoleg" || echo "Sin cambios para commitear"
          git push


